services:
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - "9117:9117"
    volumes:
      - ./config/jackett:/config
      - ./downloads:/downloads
    environment:
      - PUID=502 # Your user ID
      - PGID=20 # Your group ID
      - TZ=America/New_York
    restart: unless-stopped
    depends_on:
      - flaresolverr

